package test;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : src/main/lib/libtest.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class GoInterface extends Structure {
	/** C type : void* */
	public Pointer t;
	/** C type : void* */
	public Pointer v;
	public GoInterface() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("t", "v");
	}
	/**
	 * @param t C type : void*<br>
	 * @param v C type : void*
	 */
	public GoInterface(Pointer t, Pointer v) {
		super();
		this.t = t;
		this.v = v;
	}
	public GoInterface(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends GoInterface implements Structure.ByReference {
		
	};
	public static class ByValue extends GoInterface implements Structure.ByValue {
		
	};
}
